# Generated by Django 4.2.7 on 2024-11-18 06:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amortizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Амортизация',
                'verbose_name_plural': 'Амортизации',
                'db_table': 'Amortization',
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('chart', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Чертёж')),
                ('sketch', models.ImageField(blank=True, null=True, upload_to='proj_images', verbose_name='Эскиз')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Фото')),
                ('demonstrableForm', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Наглядное отображение')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Количество на складе')),
                ('planTime', models.TimeField(blank=True, null=True)),
                ('startDateTame', models.DateTimeField(blank=True, null=True)),
                ('finishDateTame', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Стоимость единицы')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Скидка в %')),
                ('selfCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Себестоимость')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
                'db_table': 'Component',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('chart', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Чертёж')),
                ('sketch', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Эскиз')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Фото')),
                ('demonstrableForm', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Наглядное отображение')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория оборудования',
                'verbose_name_plural': 'Категории оборудования',
                'db_table': 'EquipmentCategory',
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('time', models.TimeField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Стоимость')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=7, verbose_name='Количество')),
                ('unitTime', models.TimeField()),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Зарплата')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('amortization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.amortizations', verbose_name='Елиница')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'db_table': 'Operation',
            },
        ),
        migrations.CreateModel(
            name='OperationsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория операции',
                'verbose_name_plural': 'Категории операций',
                'db_table': 'OperationCategory',
            },
        ),
        migrations.CreateModel(
            name='OperationsStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Статус операции',
                'verbose_name_plural': 'Статусы операций',
                'db_table': 'OperationStatus',
            },
        ),
        migrations.CreateModel(
            name='Orderers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyName', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('secondName', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('dateOfBirth', models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('telephones', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Фото')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'db_table': 'Orderer',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('planTime', models.TimeField(blank=True, null=True)),
                ('startDateTame', models.DateTimeField(blank=True, null=True)),
                ('finishDateTame', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Стоимость')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Скидка в %')),
                ('selfCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Себестоимость')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('route', models.CharField(blank=True, max_length=150, null=True)),
                ('mapChart', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Чертёж')),
                ('mapSketch', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Эскиз')),
                ('mapDemonstrableForm', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Наглядное отображение')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Фото')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
                'db_table': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='UnitsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория единицы',
                'verbose_name_plural': 'Категории единиц',
                'db_table': 'UnitCategory',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyName', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('secondName', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('passport', models.CharField(blank=True, max_length=150, null=True)),
                ('dateOfBirth', models.DateTimeField()),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('telephones', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='main_images', verbose_name='Фото')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'Worker',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTimeOperation', models.DateTimeField()),
                ('finishtDateTimeOperation', models.DateTimeField(null=True)),
                ('workTime', models.TimeField(blank=True, null=True)),
                ('makeWork', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Сделано работы,с')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.operations', verbose_name='Операция')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.projects', verbose_name='Проект')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.workers', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'db_table': 'Work',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('unitCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.unitscategories', verbose_name='Категория единицы')),
            ],
            options={
                'verbose_name': 'Единица',
                'verbose_name_plural': 'Единицы',
                'db_table': 'Unit',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=datetime.datetime(2024, 11, 18, 8, 53, 57, 146675))),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Количество')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.components', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'На складе',
                'verbose_name_plural': 'На складе',
                'db_table': 'Storage',
            },
        ),
        migrations.CreateModel(
            name='ProjectsOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.operations', verbose_name='Операция')),
                ('operationStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.operationsstatuses', verbose_name='Операция')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.projects', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Операция проекта',
                'verbose_name_plural': 'Операции проектов',
                'db_table': 'ProjectOperation',
            },
        ),
        migrations.CreateModel(
            name='ProjectsComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.components', verbose_name='Категория проекта')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.projects', verbose_name='Категория проекта')),
            ],
            options={
                'verbose_name': 'Компонент проекта',
                'verbose_name_plural': 'Компоненты проектов',
                'db_table': 'ProjectComponent',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('orderer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.orderers', verbose_name='Заказчик')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Order',
            },
        ),
        migrations.AddField(
            model_name='orderers',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sources', verbose_name='Предприятие'),
        ),
        migrations.AddField(
            model_name='operations',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.operationscategories', verbose_name='Категория операции'),
        ),
        migrations.AddField(
            model_name='operations',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipments', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='operations',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.units', verbose_name='Елиница'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='equipmentCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipmentscategories', verbose_name='Категория проекта'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sources', verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='ComponentsTechCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.componentstechcategories', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Техническая категория компонента',
                'verbose_name_plural': 'Технические категории компонентов',
                'db_table': 'ComponentTechCategory',
            },
        ),
        migrations.CreateModel(
            name='ComponentsProjCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('parent', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.componentsprojcategories', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Проектная категория компонента',
                'verbose_name_plural': 'Проектные категории компонентов',
                'db_table': 'ComponentProjCategory',
            },
        ),
        migrations.CreateModel(
            name='ComponentsOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=7, verbose_name='Количество')),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.components', verbose_name='Материал')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.operations', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Операция компонента',
                'verbose_name_plural': 'Операции компонентов',
                'db_table': 'ComponentOperation',
            },
        ),
        migrations.CreateModel(
            name='ComponentsGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('note', models.TextField(blank=True, max_length=200, null=True, verbose_name='Примечания')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.componentsgoals', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Целевое назначение компонента',
                'verbose_name_plural': 'Целевые назначения компонентов',
                'db_table': 'ComponentGoal',
            },
        ),
        migrations.CreateModel(
            name='ComponentsComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=7, verbose_name='Количество')),
                ('ownerComponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='main.components', verbose_name='Источник')),
                ('partComponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembles', to='main.components', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
                'db_table': 'ComponentsComponent',
            },
        ),
        migrations.AddField(
            model_name='components',
            name='componentGoal',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.componentsgoals', verbose_name='Цель'),
        ),
        migrations.AddField(
            model_name='components',
            name='componentProjCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.componentsprojcategories', verbose_name='Проектная категория'),
        ),
        migrations.AddField(
            model_name='components',
            name='componentTechCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.componentstechcategories', verbose_name='Техническая категория'),
        ),
        migrations.AddField(
            model_name='components',
            name='owners',
            field=models.ManyToManyField(through='main.ComponentsComponents', to='main.components', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='components',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sources', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='components',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.units', verbose_name='Оценочная единица'),
        ),
        migrations.AddField(
            model_name='components',
            name='сomponentsOperations',
            field=models.ManyToManyField(through='main.ComponentsOperations', to='main.operations', verbose_name='Операции'),
        ),
        migrations.AddField(
            model_name='amortizations',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.equipments', verbose_name='Источник'),
        ),
    ]
