# Generated by Django 4.2.7 on 2024-10-26 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_storage_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 9, 36, 0, 737947)),
        ),
    ]
