# Generated by Django 4.2.7 on 2024-11-18 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_storage_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='orderer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='project',
        ),
        migrations.AlterField(
            model_name='storage',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 17, 46, 37, 875713)),
        ),
        migrations.DeleteModel(
            name='Orderers',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
