# Generated by Django 4.2.7 on 2025-01-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_orders_orderer_remove_orders_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата рождения'),
        ),
    ]
